In [1]:
import pandas as pd

/usr/lib/python3/dist-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
data=pd.read_csv('../Datasets/dataSetofHeights.csv')
data.head()

Heights Gender
0  160.377337   Male
1  177.637818   Male
2  166.258270   Male
3  182.467287   Male
4  182.368534   Male

In [3]:
data.describe()

Heights
count  1000.000000
mean    168.306355
std       9.812907
min     143.501854
25%     160.946318
50%     168.019906
75%     175.859809
max     197.707840

In [8]:
import matplotlib.pyplot as plt
%matplotlib 

Using matplotlib backend: TkAgg


In [6]:
plt.hist(data['Heights'])

(array([ 15.,  64., 131., 186., 191., 169., 145.,  77.,  17.,   5.]),
 array([143.50185376, 148.92245242, 154.34305108, 159.76364974,
        165.1842484 , 170.60484706, 176.02544572, 181.44604438,
        186.86664304, 192.2872417 , 197.70784036]),
 <BarContainer object of 10 artists>)

In [7]:
plt.hist(data['Heights'],cumulative=True)

(array([  15.,   79.,  210.,  396.,  587.,  756.,  901.,  978.,  995.,
        1000.]),
 array([143.50185376, 148.92245242, 154.34305108, 159.76364974,
        165.1842484 , 170.60484706, 176.02544572, 181.44604438,
        186.86664304, 192.2872417 , 197.70784036]),
 <BarContainer object of 10 artists>)

In [9]:
data.describe()

Heights
count  1000.000000
mean    168.306355
std       9.812907
min     143.501854
25%     160.946318
50%     168.019906
75%     175.859809
max     197.707840

In [19]:
deviation=data['Heights']-data['Heights'].mean()

deviation


0      -7.929018
1       9.331463
2      -2.048084
3      14.160933
4      14.062179
         ...    
995     1.775239
996    -8.328177
997   -17.637951
998    -4.320811
999    -7.895217
Name: Heights, Length: 1000, dtype: float64

In [ ]:
import numpy as np

In [24]:
meanabso=(abs(data['Heights']-data['Heights'].mean())).mean()
meanabso

8.134686902556256

In [26]:
variance=((data['Heights']-data['Heights'].mean())**2).mean()
variance

96.19684201398101

In [27]:
import math

In [28]:
std=math.sqrt(variance)

In [29]:
std

9.807998879179229

In [30]:
data.describe()

Heights
count  1000.000000
mean    168.306355
std       9.812907
min     143.501854
25%     160.946318
50%     168.019906
75%     175.859809
max     197.707840

In [ ]:
import numpy as np 
np.std(data['Heights'])